version: "3.1"

services:
  memegen:
    build:
      context: .
      dockerfile: Containerfile
    pull_policy: build
    environment:
      PORT: $PORT
      DOMAIN: $DOMAIN
    ports:
      - $PORT:$PORT
    restart: on-failure:10
